version: '3'

services:
  api-budget:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: budget
    ports:
      - 3006:3006
    volumes:
      - .:/home/node/app
    tty: true
    depends_on:
      - db
    networks:
      - budget-network

  db:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - /mongodb/dbdata:/data/db
      - /mongodb/configdb:/data/configdb
    environment:
      #      MONGO_INITDB_ROOT_USERNAME: root
      #      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: budget
    networks:
      - budget-network

  # redis:
  #   image: 'redis:latest'
  #   container_name: 'redis-container'
  #   ports:
  #     - '6379:6379'

networks:
  budget-network:
    driver: bridge